(function() {var implementors = {};
implementors["chrono"] = [];
implementors["hyper"] = ["impl&lt;S&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a> for <a class='struct' href='openssl/ssl/struct.SslStream.html' title='openssl::ssl::SslStream'>SslStream</a>&lt;S&gt; <span class='where fmt-newline'>where S: <a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a></span>","impl&lt;S&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a> for <a class='struct' href='openssl/ssl/struct.NonblockingSslStream.html' title='openssl::ssl::NonblockingSslStream'>NonblockingSslStream</a>&lt;S&gt; <span class='where fmt-newline'>where S: <a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a></span>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a> for <a class='struct' href='hyper/net/struct.HttpListener.html' title='hyper::net::HttpListener'>HttpListener</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a> for <a class='struct' href='hyper/net/struct.HttpStream.html' title='hyper::net::HttpStream'>HttpStream</a>",];
implementors["libc"] = [];
implementors["num"] = [];
implementors["openssl"] = ["impl&lt;S:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a> for <a class='struct' href='openssl/ssl/struct.SslStream.html' title='openssl::ssl::SslStream'>SslStream</a>&lt;S&gt;","impl&lt;S:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a> for <a class='struct' href='openssl/ssl/struct.NonblockingSslStream.html' title='openssl::ssl::NonblockingSslStream'>NonblockingSslStream</a>&lt;S&gt;",];
implementors["serde"] = [];
implementors["vkrs"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a> for <a class='struct' href='hyper/net/struct.HttpListener.html' title='hyper::net::HttpListener'>HttpListener</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a> for <a class='struct' href='hyper/net/struct.HttpStream.html' title='hyper::net::HttpStream'>HttpStream</a>","impl&lt;S&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a> for <a class='struct' href='openssl/ssl/struct.SslStream.html' title='openssl::ssl::SslStream'>SslStream</a>&lt;S&gt; <span class='where fmt-newline'>where S: <a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a></span>","impl&lt;S&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a> for <a class='struct' href='openssl/ssl/struct.NonblockingSslStream.html' title='openssl::ssl::NonblockingSslStream'>NonblockingSslStream</a>&lt;S&gt; <span class='where fmt-newline'>where S: <a class='trait' href='https://doc.rust-lang.org/nightly/std/sys/imp/ext/io/trait.AsRawFd.html' title='std::sys::imp::ext::io::AsRawFd'>AsRawFd</a></span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
